USE [master]
GO

/****** Object:  Database [CleanedAdventureWorks]    Script Date: 9/17/2025 5:55:12 PM ******/
CREATE DATABASE [CleanedAdventureWorks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CleanedAdventureWorks', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CleanedAdventureWorks.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CleanedAdventureWorks_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CleanedAdventureWorks_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CleanedAdventureWorks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CleanedAdventureWorks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET ARITHABORT OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CleanedAdventureWorks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CleanedAdventureWorks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CleanedAdventureWorks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CleanedAdventureWorks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CleanedAdventureWorks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CleanedAdventureWorks] SET  MULTI_USER 
GO

ALTER DATABASE [CleanedAdventureWorks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CleanedAdventureWorks] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CleanedAdventureWorks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CleanedAdventureWorks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CleanedAdventureWorks] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CleanedAdventureWorks] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CleanedAdventureWorks] SET QUERY_STORE = ON
GO

ALTER DATABASE [CleanedAdventureWorks] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CleanedAdventureWorks] SET  READ_WRITE 
GO

